In [3]:
!pip install torch

     |███████████▉                    | 327.9 MB 94.3 MB/s eta 0:00:066  |█                               | 25.5 MB 4.8 MB/s eta 0:03:01     |█████▍                          | 150.1 MB 109.3 MB/s eta 0:00:07

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



     |████████████████████▊           | 574.9 MB 133.4 MB/s eta 0:00:03

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



     |██████████████████████████▏     | 727.8 MB 122.3 MB/s eta 0:00:02

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



     |████████████████████████████████| 890.2 MB 8.7 kB/s s eta 0:00:01
     |███████████████████████████▊    | 274.8 MB 132.3 MB/s eta 0:00:01

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



     |████████████████████████████████| 317.1 MB 30 kB/s 
     |█████████████████▋              | 305.9 MB 116.6 MB/s eta 0:00:03

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



     |████████████████████████████████| 557.1 MB 8.5 kB/s  eta 0:00:01
     |████████████████████████████████| 849 kB 110.8 MB/s eta 0:00:01
     |████████████████████████████████| 21.0 MB 103.0 MB/s eta 0:00:01


In [11]:
import torch
import numpy as np

In [5]:
# ０階テンソル（スカラー）
r0 = torch.tensor(1.0).float()

In [6]:
type(r0)

torch.Tensor

In [7]:
r0.dtype

torch.float32

In [9]:
r0.data

tensor(1.)

In [12]:
# １階テンソル（ベクトル）
r1_np = np.array([1, 2, 3, 4, 5])
r1_np.shape

(5,)

In [13]:
# numpyからテンソルに変換
r1 = torch.tensor(r1_np).float()
r1.dtype

torch.float32

In [14]:
r1.shape

torch.Size([5])

In [15]:
r1.data

tensor([1., 2., 3., 4., 5.])

In [16]:
# ２階テンソル（行列）
r2_np = np.array([[1, 5, 6], [4, 3, 2]])
r2_np.shape

(2, 3)

In [18]:
# numpyからテンソルに変換
r2 = torch.tensor(r2_np).float()
print(r2.dtype)
print(r2.shape)
print(r2.data)

torch.float32
torch.Size([2, 3])
tensor([[1., 5., 6.],
        [4., 3., 2.]])


In [21]:
# ３階テンソル
# 乱数seedの初期化
torch.manual_seed(123)

# shape=[3,2,2]の正規分布変数テンソル
r3 = torch.randn((3, 2, 2))
r3.shape

torch.Size([3, 2, 2])

In [22]:
print(r3.shape)
print(r3.data)

torch.Size([3, 2, 2])
tensor([[[-0.1115,  0.1204],
         [-0.3696, -0.2404]],

        [[-1.1969,  0.2093],
         [-0.9724, -0.7550]],

        [[ 0.3239, -0.1085],
         [ 0.2103, -0.3908]]])


In [24]:
# ４階テンソル
# shape=[2,3,2,2]の要素がすべて１のテンソル
r4 = torch.ones((2, 3, 2, 2))
print(r4.shape)
print(r4.data)

torch.Size([2, 3, 2, 2])
tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])
